#!/usr/bin/perl -w

$bindir = shift @ARGV;
$srcdir = shift @ARGV;

# In-place substitution using Perl (avoids BSD sed vs GNU sed incompatibility)
{
	local $^I = '';
	local @ARGV = ("$bindir/pddl+.cpp");
	while (<>) {
		s/yyerror\(char/yyerror(const char/g;
		print;
	}
}

open IN, "g++ -E $srcdir/fixyywrap.cpp |";
open OUT, "> $bindir/fixyywrap.h";

while (<IN>) {

	if (m/int yywrap/) {
		print OUT "#ifndef __APPLE__\n";
		print OUT "int yyFlexLexer::yywrap() { return 1; };\n";
		print OUT "#endif\n";
	}

}

close IN;
close OUT;

open OUT, ">> $bindir/pddl+.cpp";
print OUT '#include "fixyywrap.h"';
print OUT "\n\n";
close OUT;

